# Pandas

In [2]:

import pandas as pd

In [3]:
print(pd.__version__)

3.0.6

In [4]:
s = pd.Series([90,85,72])

In [5]:
print(s)

0    90
1    85
2    72
dtype: int64

In [6]:
import pandas as pd

In [7]:
# Series: a single labelled column
s = pd.Series([90,85,72],
             index=["Amit", "Riya", "Sam"])


# DataFrame: builf from a dictionary

data = {
    "name": ["Amit", "Riya", "Sam"],
    "marks":[90,85,72],
    "city":["Delhi","Pune","Goa"],
}
df = pd.DataFrame(data)

In [8]:
print(df)

   name  marks   city
0  Amit     90  Delhi
1  Riya     85   Pune
2   Sam     72    Goa

In [9]:
data = {
    "name": ["Amit", "Riya", "Sam" , "Yashika", "Sonu", "Kafi", "Aman", "Ritika", "Karan", "Irfana"],
    "marks":[90,85,72,52,85,63,895,96,74,21],
    "city":["Delhi","Pune","Goa","Gujrat","London","America","Canada","Mumbai","Chandigarh","Rajasthan"],
}
df = pd.DataFrame(data)
print(df)

      name  marks        city
0     Amit     90       Delhi
1     Riya     85        Pune
2      Sam     72         Goa
3  Yashika     52      Gujrat
4     Sonu     85      London
5     Kafi     63     America
6     Aman    895      Canada
7   Ritika     96      Mumbai
8    Karan     74  Chandigarh
9   Irfana     21   Rajasthan

In [10]:
df.head(8)

      name  marks     city
0     Amit     90    Delhi
1     Riya     85     Pune
2      Sam     72      Goa
3  Yashika     52   Gujrat
4     Sonu     85   London
5     Kafi     63  America
6     Aman    895   Canada
7   Ritika     96   Mumbai

In [11]:
df.tail(4)

     name  marks        city
6    Aman    895      Canada
7  Ritika     96      Mumbai
8   Karan     74  Chandigarh
9  Irfana     21   Rajasthan

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10 non-null     str
 1   marks   10 non-null     int64
 2   city    10 non-null     str
dtypes: int64(1), str(2)
memory usage: 372.0 bytes

In [13]:
df.columns

Index(['name', 'marks', 'city'], dtype='str')

In [14]:
df.describe()

            marks
count   10.000000
mean   153.300000
std    261.524611
min     21.000000
25%     65.250000
50%     79.500000
75%     88.750000
max    895.000000

In [15]:
df.shape

(10, 3)

In [16]:
df.columns

Index(['name', 'marks', 'city'], dtype='str')